### ISSUE TITLE
Small suggestion about txtMessages

### ISSUE THREAD

**Issue by zhao0876** [spotware/Open-API-2.0-.Net-Sample#2]
This code
                txtMessages.Text += "Send: " + OpenApiMessagesPresentation.ToString(msg);
                txtMessages.Text += Environment.NewLine;
It is better to write this way：
                txtMessages.AppendText("Send: " + OpenApiMessagesPresentation.ToString(msg) + Environment.NewLine);

After the textbox  appended  text, it will stay in the first line. 
It is not convenient to observe the information. 
After rewriting, it will stay in the last line.

**Comment by PanagiotisChar** [comment]
Done
